# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  # Used for loading and caching images
  pod 'SDWebImage', '~> 4.0'
end
